import { Subject } from "./types";

export const SUBJECTS: Subject[] = [
  {
    id: "english",
    name: "English",
    weightage: 20,
    color: "#6c63ff",
    icon: "📝",
    topics: [
      "Grammar & Sentence Structure",
      "Synonyms & Antonyms",
      "Reading Comprehension",
      "Sentence Correction",
      "Active & Passive Voice",
      "Direct & Indirect Speech",
      "Fill in the Blanks",
      "One Word Substitution",
      "Idioms & Phrases",
      "Prepositions & Articles",
    ],
  },
  {
    id: "general_knowledge",
    name: "General Knowledge",
    weightage: 20,
    color: "#00d4aa",
    icon: "🌍",
    topics: [
      "World Affairs & Current Events",
      "United Nations & International Organizations",
      "OIC, NATO, SAARC",
      "World Capitals & Currencies",
      "Important Days & Dates",
      "Scientific Discoveries",
      "Nobel Prize Winners",
      "Famous Personalities",
      "World Geography",
      "Sports & Olympics",
    ],
  },
  {
    id: "math_iq",
    name: "Math / IQ",
    weightage: 20,
    color: "#ffd700",
    icon: "🧮",
    topics: [
      "Percentages & Ratios",
      "Profit & Loss",
      "Simple & Compound Interest",
      "Number Series",
      "Coding-Decoding",
      "Analogies & Odd One Out",
      "Time & Work",
      "Speed, Distance & Time",
      "Algebra Basics",
      "Logical Reasoning",
    ],
  },
  {
    id: "pakistan_studies",
    name: "Pakistan Studies",
    weightage: 10,
    color: "#e94560",
    icon: "🇵🇰",
    topics: [
      "Independence Movement",
      "Ideology of Pakistan",
      "Constitution of Pakistan",
      "Geography of Pakistan",
      "Rivers & Dams",
      "CPEC & Economy",
      "Famous Personalities",
      "Administrative Divisions",
      "National Symbols",
      "Important Events in History",
    ],
  },
  {
    id: "islamic_studies",
    name: "Islamic Studies",
    weightage: 10,
    color: "#ff9500",
    icon: "☪️",
    topics: [
      "Five Pillars of Islam",
      "Holy Quran & Surahs",
      "Seerah of Prophet (PBUH)",
      "Khulfa-e-Rashideen",
      "Islamic History",
      "Hadith & Sunnah",
      "Islamic Calendar & Events",
      "Companions of Prophet",
      "Islamic Jurisprudence Basics",
      "Ethics & Moral Values",
    ],
  },
  {
    id: "computer_it",
    name: "Computer / IT",
    weightage: 10,
    color: "#00bcd4",
    icon: "💻",
    topics: [
      "MS Word & Formatting",
      "MS Excel & Formulas",
      "MS PowerPoint",
      "Internet & Email",
      "Hardware & Software",
      "Operating Systems",
      "Database Basics",
      "Networking Fundamentals",
      "Cybersecurity Basics",
      "Artificial Intelligence Concepts",
    ],
  },
  {
    id: "current_affairs",
    name: "Current Affairs",
    weightage: 10,
    color: "#ff6b6b",
    icon: "📰",
    topics: [
      "Pakistan Political Affairs",
      "Pakistan Economic News",
      "International Relations",
      "Military & Defence",
      "Science & Technology News",
      "Environment & Climate",
      "Sports News",
      "Social Issues Pakistan",
      "Regional Affairs (South Asia)",
      "Global Economic Trends",
    ],
  },
];

export const FIFTEEN_DAY_PLAN = [
  { day: 1, focus: "english", title: "Diagnostic + English Basics", mcq_count: 200, has_test: true },
  { day: 2, focus: "general_knowledge", title: "English Advanced + GK", mcq_count: 250, has_test: true },
  { day: 3, focus: "pakistan_studies", title: "Pakistan Studies Deep Dive", mcq_count: 250, has_test: true },
  { day: 4, focus: "islamic_studies", title: "Islamic Studies", mcq_count: 250, has_test: true },
  { day: 5, focus: "math_iq", title: "Math / IQ Part 1", mcq_count: 300, has_test: true },
  { day: 6, focus: "math_iq", title: "Math / IQ Part 2", mcq_count: 300, has_test: true },
  { day: 7, focus: "computer_it", title: "Computer & IT", mcq_count: 250, has_test: true },
  { day: 8, focus: "current_affairs", title: "Current Affairs Deep Dive", mcq_count: 300, has_test: true },
  { day: 9, focus: "mock", title: "Full Mock Exam #1", mcq_count: 100, has_test: false },
  { day: 10, focus: "weak", title: "Weak Area Drilling", mcq_count: 300, has_test: true },
  { day: 11, focus: "mock", title: "Full Mock Exam #2", mcq_count: 100, has_test: false },
  { day: 12, focus: "interview", title: "Interview Prep — HR Questions", mcq_count: 0, has_test: false },
  { day: 13, focus: "interview", title: "Interview Prep — Subject Questions", mcq_count: 0, has_test: false },
  { day: 14, focus: "mock", title: "Full Mock Exam #3 + Revision", mcq_count: 100, has_test: false },
  { day: 15, focus: "revision", title: "Light Revision + Confidence Boost", mcq_count: 50, has_test: false },
];
